### ISSUE TITLE
stack_data / tracebacks

### ISSUE THREAD

**Issue by alexmojaki** [gsmecher/awaitless#2]
Responding to https://github.com/ipython/ipython/issues/13598#issuecomment-2302693223

Your extension transforms `hello()` into

```python

_ttemp = hello()
if inspect.iscoroutine(_ttemp):
    _ttemp = asyncio.create_task(_ttemp)
    await _ttemp
_ttemp
```

When `hello()` raises an exception, the traceback points to line 5 (`await _ttemp`). But the only source code available is `hello()` which only has one line. `stack_data` is failing because it can't find the nonexistent source code. Nothing possibly could.

Worse, if the user enters an expression that actually has 5 lines, there will be no error, the traceback will just silently point at the wrong line. I can confirm this:

```python
In [6]: hello(
   ...: 1,
   ...: 2,
   ...: 3,
   ...: 4,
   ...: 5,
   ...: 6)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[6], line 5
      1 hello(
      2 1,
      3 2,
      4 3,
----> 5 4,
      6 5,
      7 6)

Cell In[4], line 1, in hello(*_)
----> 1 async def hello(*_): raise Exception("uh oh")
```

A simple fix would be to define a function `maybe_await` and then always transform `x` into `await maybe_await(x)`. Then the traceback would always point to line 1 of the interactive cell (that can't go wrong) as well as to the body of `maybe_await` making the magic less invisible and mysterious:

```python
In [7]: async def maybe_await(x):
   ...:     import asyncio
   ...:     import inspect
   ...: 
   ...:     if inspect.iscoroutine(x):
   ...:         x = asyncio.create_task(x)
   ...:         await x
   ...:     return x
   ...: 

In [8]: await maybe_await(hello(
   ...: 1,
   ...: 2))
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 await maybe_await(hello(
      2 1,
      3 2))

Cell In[7], line 7, in maybe_await(x)
      5 if inspect.iscoroutine(x):
      6     x = asyncio.create_task(x)
----> 7     await x
      8 return x

Cell In[4], line 1, in hello(*_)
----> 1 async def hello(*_): raise Exception("uh oh")

Exception: uh oh
```

**Comment by gsmecher** [comment]
Ah - I see. There's some amount of "no good deed goes unpunished" associated with open-source code. I should have begun with a "thanks for your work". Also, now, thanks for your time on this little project.

I had hoped ast.copy_location() would do a good job of fixing this - let me see if I can come up with something.
